# Generated by Django 3.2.13 on 2022-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0)),
                ('roads', models.IntegerField(default=0)),
                ('trees', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0)),
                ('hospitals', models.IntegerField(default=0)),
                ('national_parks', models.IntegerField(default=0)),
            ],
        ),
    ]
